# Generated by Django 4.2.19 on 2025-03-03 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('content', models.TextField()),
                ('image1', models.ImageField(upload_to='works/project')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='works/project')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='works/project')),
            ],
        ),
    ]
